# Generated by Django 5.1.5 on 2025-02-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_post_photo_reel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='reel',
            old_name='content',
            new_name='description',
        ),
    ]
